### PR TITLE
Add a bunch of introducintroductory angular assignments

### PR DESCRIPTION
**Pull request by alarner**
I put together a bunch of introductory angular assignments to teach some of the really common directives as well as how to use controllers and modules. More coming soon. This is my first PR to the js-assignments repo so please let me know if there's some other protocol I should be following.

### CODE REVIEW

**Comment by calweb** [comment]
@alarner these are awesome!  Thanks for getting them up on here.  I especially like the form validation ones! :+1:

**Comment by masondesu** [comment]
Looks awesome.

**Comment by matthiasak** [comment]
:+1:

**Comment by twhitacre** [comment]
@alarner appreciate you putting these together. I will probably use some of them this week.

**Pull request merged**
